# ================= 加载国家数据库 =================
geoip2 /usr/local/nginx/geoip/GeoLite2-Country.mmdb {
    auto_reload 60m;                          # Nginx ≥1.19.3 支持自动重载更新后的 DB
    $geoip2_data_country_code default=Unknown source=$remote_addr country iso_code;
    $geoip2_data_country_name country names en;
}

# ================= 加载城市数据库 =================
geoip2 /usr/local/nginx/geoip/GeoLite2-City.mmdb {
    auto_reload 60m;
    $geoip2_data_city_name default=Unknown source=$remote_addr city names en;
    $geoip2_data_region_name subdivisions 0 names en;
    $geoip2_data_latitude location latitude;
    $geoip2_data_longitude location longitude;
    $geoip2_data_time_zone location time_zone;
}